spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/demo_app
    username: test
    password: test
  flyway:
    url: jdbc:postgresql://localhost:5435/demo_app
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true