title: Martin Mašata
description: My Personal Page
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
linkedin_url: https://www.linkedin.com/in/martin-masata/
github:
  profile_url: https://github.com/mmasata